const {pool}=require('../config/db');const {success,failure}=require('../utils/apiResponse');const asyncHandler=require('../utils/asyncHandler');
const config={
 destinations:['name','city','state','country','description','category','climate','best_season','minimum_budget','average_daily_cost','image','latitude','longitude','rating','status'],
 hotels:['destination_id','name','description','location','price_per_night','rating','hotel_type','room_type','maximum_guests','amenities','image','contact','availability_status'],
 restaurants:['destination_id','name','description','location','cuisine','average_cost_per_person','rating','dietary_options','opening_time','closing_time','image','status'],
 attractions:['destination_id','name','description','location','category','entry_fee','recommended_duration','opening_time','closing_time','best_visit_time','rating','image','latitude','longitude','status'],
 transportation:['origin','destination_id','transport_type','provider','estimated_cost','estimated_duration','description','status'],
 travel_packages:['destination_id','name','description','days','base_price','inclusions','status'],
 bookings:['booking_type','provider_reference','booking_date','amount','currency','status','notes'],
 reviews:['rating','title','comment','status'],
 trips:['title','start_date','end_date','traveller_count','status']
};
function table(req){const t=req.params.resource;if(!config[t])throw Object.assign(new Error('Unsupported admin resource'),{statusCode:400});return t;}
const stats=asyncHandler(async(req,res)=>{const names=['users','destinations','hotels','restaurants','attractions','trips','bookings','reviews','ai_messages','ai_request_logs'];const out={};for(const n of names){const [[r]]=await pool.query(`SELECT COUNT(*) count FROM ${n}`);out[n]=r.count;}const [recent]=await pool.query('SELECT DATE(created_at) day,COUNT(*) count FROM trips GROUP BY DATE(created_at) ORDER BY day DESC LIMIT 14');const [aiBreakdown]=await pool.query('SELECT endpoint,source,status,COUNT(*) count,ROUND(AVG(duration_ms)) average_ms FROM ai_request_logs GROUP BY endpoint,source,status ORDER BY count DESC');return success(res,{counts:out,recentTrips:recent,aiBreakdown});});
const list=asyncHandler(async(req,res)=>{const t=table(req);const page=Math.max(1,Number(req.query.page)||1),limit=20,offset=(page-1)*limit;const search=String(req.query.search||'').trim();const searchable=config[t].map(f=>`CAST(${f} AS CHAR)`).join(',');const where=search?` WHERE CONCAT_WS(' ',${searchable}) LIKE ?`:'';const params=search?[`%${search}%`,limit,offset]:[limit,offset];const [rows]=await pool.query(`SELECT * FROM ${t}${where} ORDER BY id DESC LIMIT ? OFFSET ?`,params);const countParams=search?[`%${search}%`]:[];const [[c]]=await pool.query(`SELECT COUNT(*) total FROM ${t}${where}`,countParams);return success(res,{items:rows,pagination:{page,limit,total:c.total,pages:Math.max(1,Math.ceil(c.total/limit))}});});
const create=asyncHandler(async(req,res)=>{const t=table(req),fields=config[t].filter(k=>req.body[k]!==undefined);if(req.file&&!fields.includes('image'))fields.push('image');if(!fields.length)return failure(res,'No fields supplied',400);const vals=fields.map(k=>k==='image'&&req.file?`/uploads/${req.file.filename}`:req.body[k]);const [r]=await pool.query(`INSERT INTO ${t} (${fields.join(',')}) VALUES (${fields.map(()=>'?').join(',')})`,vals);return success(res,{id:r.insertId},'Record created',201);});
const update=asyncHandler(async(req,res)=>{const t=table(req),fields=config[t].filter(k=>req.body[k]!==undefined);if(req.file&&!fields.includes('image'))fields.push('image');if(!fields.length)return failure(res,'No fields supplied',400);const vals=fields.map(k=>k==='image'&&req.file?`/uploads/${req.file.filename}`:req.body[k]);vals.push(req.params.id);await pool.query(`UPDATE ${t} SET ${fields.map(k=>`${k}=?`).join(',')} WHERE id=?`,vals);return success(res,null,'Record updated');});
const remove=asyncHandler(async(req,res)=>{const t=table(req);await pool.query(`DELETE FROM ${t} WHERE id=?`,[req.params.id]);return success(res,null,'Record deleted');});
const users=asyncHandler(async(req,res)=>{const [r]=await pool.query('SELECT id,name,email,phone,role,status,last_login_at,created_at FROM users ORDER BY id DESC');return success(res,r);});
const updateUser=asyncHandler(async(req,res)=>{await pool.execute('UPDATE users SET role=COALESCE(?,role),status=COALESCE(?,status) WHERE id=?',[req.body.role||null,req.body.status||null,req.params.id]);return success(res,null,'User updated');});
const moderateReview=asyncHandler(async(req,res)=>{await pool.execute('UPDATE reviews SET status=? WHERE id=?',[req.body.status,req.params.id]);return success(res,null,'Review moderated');});
module.exports={stats,list,create,update,remove,users,updateUser,moderateReview};
