const { body }=require('express-validator'); const {pool}=require('../config/db'); const {callChat}=require('../services/groqService'); const {success}=require('../utils/apiResponse'); const asyncHandler=require('../utils/asyncHandler'); const {generatePlan}=require('../services/recommendationService');
async function logAi(userId,endpoint,source,status,started,error=null){try{await pool.execute('INSERT INTO ai_request_logs (user_id,endpoint,source,status,duration_ms,error_message) VALUES (?,?,?,?,?,?)',[userId,endpoint,source,status,Date.now()-started,error?String(error.message||error).slice(0,500):null]);}catch(logError){console.warn('AI log failed:',logError.message);}}
const planHandler=(endpoint)=>asyncHandler(async(req,res)=>{const started=Date.now();try{const plan=await generatePlan(req.body);await logAi(req.user.id,endpoint,plan.ai.source,'success',started);return success(res,plan,'Itinerary generated');}catch(error){await logAi(req.user.id,endpoint,'fallback','error',started,error);throw error;}});
const generate=planHandler('generate-itinerary');
const recommend=planHandler('recommend');
const optimize=planHandler('optimize-budget');
const regenerateDay=asyncHandler(async(req,res)=>{const started=Date.now();try{const plan=await generatePlan({...req.body,days:1,startDate:req.body.date,endDate:req.body.date,title:`Regenerated Day ${req.body.dayNumber||1}`});await logAi(req.user.id,'regenerate-day',plan.ai.source,'success',started);return success(res,plan.itinerary[0],'Day regenerated');}catch(error){await logAi(req.user.id,'regenerate-day','fallback','error',started,error);throw error;}});
const chat=asyncHandler(async(req,res)=>{
 const started=Date.now(); const message=String(req.body.message||'').trim(); const [destinations]=await pool.execute('SELECT id,name,city,state,country,minimum_budget,average_daily_cost,best_season FROM destinations WHERE status="active" ORDER BY rating DESC LIMIT 25');
 let answer='I can help you compare destinations and budgets using the TripGenie catalogue.'; let source='fallback';
 if(message){
   try { const ai=await callChat({message,destinations}); if(ai.answer){answer=ai.answer;source='groq';} }
   catch(error){ const lower=message.toLowerCase();const matches=destinations.filter(d=>lower.includes(d.name.toLowerCase())||lower.includes(d.city.toLowerCase()));if(matches.length)answer=matches.map(d=>`${d.name}: minimum trip budget ₹${d.minimum_budget}, typical daily cost ₹${d.average_daily_cost}, best season ${d.best_season}.`).join('\n');else answer=`Based on the active TripGenie catalogue, consider ${destinations.slice(0,3).map(d=>d.name).join(', ')}. Use Plan Trip to receive a database-grounded itinerary.`; }
 }
 const conn=await pool.getConnection();try{await conn.beginTransaction();let conversationId=Number(req.body.conversationId)||null;if(!conversationId){const [r]=await conn.execute('INSERT INTO ai_conversations (user_id,title) VALUES (?,?)',[req.user.id,message.slice(0,80)||'Travel chat']);conversationId=r.insertId;}await conn.execute('INSERT INTO ai_messages (conversation_id,role,content) VALUES (?,?,?)',[conversationId,'user',message]);await conn.execute('INSERT INTO ai_messages (conversation_id,role,content) VALUES (?,?,?)',[conversationId,'assistant',answer]);await conn.commit();await logAi(req.user.id,'chat',source,'success',started);return success(res,{conversationId,answer,groundedDestinations:destinations.slice(0,5),source});}catch(e){await conn.rollback();await logAi(req.user.id,'chat',source,'error',started,e);throw e;}finally{conn.release();}
});
module.exports={generate,recommend,optimize,regenerateDay,chat};
