const {pool}=require('../config/db');const {success,failure}=require('../utils/apiResponse');const asyncHandler=require('../utils/asyncHandler');
const listFavourites=asyncHandler(async(req,res)=>{const [r]=await pool.execute(`SELECT f.*,COALESCE(d.name,h.name,r.name,a.name) item_name,COALESCE(d.image,h.image,r.image,a.image) image FROM favourites f LEFT JOIN destinations d ON f.item_type='destination' AND d.id=f.item_id LEFT JOIN hotels h ON f.item_type='hotel' AND h.id=f.item_id LEFT JOIN restaurants r ON f.item_type='restaurant' AND r.id=f.item_id LEFT JOIN attractions a ON f.item_type='attraction' AND a.id=f.item_id WHERE f.user_id=? ORDER BY f.created_at DESC`,[req.user.id]);return success(res,r);});
const addFavourite=asyncHandler(async(req,res)=>{await pool.execute('INSERT IGNORE INTO favourites (user_id,item_type,item_id) VALUES (?,?,?)',[req.user.id,req.body.itemType,req.body.itemId]);return success(res,null,'Added to favourites',201);});
const removeFavourite=asyncHandler(async(req,res)=>{await pool.execute('DELETE FROM favourites WHERE user_id=? AND item_type=? AND item_id=?',[req.user.id,req.params.type,req.params.id]);return success(res,null,'Removed from favourites');});
const reviews=asyncHandler(async(req,res)=>{const [r]=await pool.execute('SELECT r.*,u.name user_name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.status="approved" AND (? IS NULL OR r.item_type=?) AND (? IS NULL OR r.item_id=?) ORDER BY r.created_at DESC',[req.query.type||null,req.query.type||null,req.query.itemId||null,req.query.itemId||null]);return success(res,r);});
const addReview=asyncHandler(async(req,res)=>{const [r]=await pool.execute('INSERT INTO reviews (user_id,item_type,item_id,rating,title,comment,status) VALUES (?,?,?,?,?,?,"pending")',[req.user.id,req.body.itemType,req.body.itemId,req.body.rating,req.body.title||null,req.body.comment]);return success(res,{id:r.insertId},'Review submitted for moderation',201);});
const bookings=asyncHandler(async(req,res)=>{const [r]=await pool.execute('SELECT * FROM bookings WHERE user_id=? ORDER BY created_at DESC',[req.user.id]);return success(res,r);});
const addBooking=asyncHandler(async(req,res)=>{const b=req.body;const [r]=await pool.execute(`INSERT INTO bookings (user_id,trip_id,booking_type,related_record_id,provider_reference,booking_date,amount,currency,status,notes) VALUES (?,?,?,?,?,?,?,?,?,?)`,[req.user.id,b.tripId||null,b.bookingType,b.relatedRecordId||null,b.providerReference||null,b.bookingDate,b.amount||0,b.currency||'INR',b.status||'pending',b.notes||null]);return success(res,{id:r.insertId},'Booking recorded',201);});
module.exports={listFavourites,addFavourite,removeFavourite,reviews,addReview,bookings,addBooking};
